version: '3.8'

services:
  app:
    image: registry.t00x.com/sql_xss_task:latest
    build: .
    ports:
      - 8080:5005
    restart: always
    depends_on: 
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    